apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: aws-secret-pre-install-job
    spec:
      restartPolicy: Never
      serviceAccountName: sa-health-check
      containers:
        - name: job-container
          image: {{ .Values.job.image }}
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: test-gateway-secret
            - configMapRef:
                name: test-gateway-configmap
          command: ["sh", "-c"]
          args:
            - |
              echo "Debug: Hook is executed"
              # Delete the existing secret if it exists (ignore errors if not found)
              kubectl delete secret regcred --ignore-not-found -n default
              
              # Create new secret
              kubectl create secret docker-registry regcred \
              --docker-server=735595018165.dkr.ecr.us-east-1.amazonaws.com \
              --docker-username=AWS \
              --docker-password=$(aws ecr get-login-password --region us-east-1 | cut -d' ' -f6) \
              --namespace=default
              
              # Add other container settings as needed
