apiVersion: batch/v1
kind: Job
metadata:
  name: aws-secret-pre-install-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: aws-secret-pre-install-job
    spec:
      imagePullSecrets:
        - name: awsecr-cred
      containers:
        - name: job-container
          image: 735595018165.dkr.ecr.us-east-1.amazonaws.com/gateway:0.0.1
          command: ["sh", "-c"]
          args:
            - "echo 'Debug: Hook is executed' && sleep 120"
      restartPolicy: Never

