apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-gateway.fullname" . }}
  labels:
    {{- include "test-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      nodePort: 30038
      port: 8761
      protocol: TCP
      targetPort: http
  selector:
    {{- include "test-gateway.selectorLabels" . | nindent 4 }}
