apiVersion: batch/v1
kind: Job
metadata:
  name: aws-secret-pre-install-job
spec:
  template:
    metadata:
      name: aws-secret-pre-install-job
    spec:
      containers:
        - name: job-container
          image: your-job-image:tag
          command: ["sh", "-c"]
          args:
            - |
              # Delete the existing secret if it exists (ignore errors if not found)
              kubectl delete secret my-secret-name --ignore-not-found=true
              
              # Create a new secret
              kubectl create secret generic my-secret-name \
                --from-literal=secret-key1=secret-value1 \
                --from-literal=secret-key2=secret-value2
          # Add other container settings as needed
      restartPolicy: Never
