apiVersion: v1
kind: Secret
metadata:
  name: test-gateway-secret-env
type: Opaque
data:
  # It's mandatory to encode secret key and access key to Base64 string manually using https://www.base64encode.org/
  SECRET_KEY: <key_value>
  ACCESS_KEY: <key_value>
